# Generated by Django 5.0.6 on 2024-06-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_brand_image_alter_carousel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='order_id',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
