# Generated by Django 5.0.6 on 2024-06-17 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_client_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='order_id',
        ),
    ]
