# Generated by Django 5.0.6 on 2024-06-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_billing_address_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_address',
            name='use_same_address_for_shipping',
            field=models.BooleanField(default=False),
        ),
    ]
