# Generated by Django 5.0.6 on 2024-06-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_billing_address_use_same_address_for_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_address',
            name='gst_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
