# Generated by Django 5.0.6 on 2024-06-17 09:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_billing_address_gst_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='billing_address',
            new_name='BillingAddress',
        ),
        migrations.RenameModel(
            old_name='shipping_address',
            new_name='ShippingAddress',
        ),
    ]
